In [8]:
#現在のディレクトリを確認
import os
current_directory = os.getcwd()
print("Current working directory:", current_directory)

Current working directory: /Users/sawad/dev/myapps/u-on-zu_data-processing

In [9]:
#出力先ディレクトリの設定
output_dir = './processed'

In [2]:
import pandas as pd

df=pd.read_csv('./raw/11_宗谷_utf-8.csv', encoding='utf-8', header=None)

display(df.head(30))

,0,1,2,3,4,5,6,7,8,9,...,125,126,127,128,129,130,131,132,133,134
0,ダウンロードした時刻：2024/05/28 13:23:20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,...,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷
3,NaN,宗谷岬,宗谷岬,宗谷岬,宗谷岬,宗谷岬,宗谷岬,宗谷岬,宗谷岬,宗谷岬,...,歌登,歌登,歌登,歌登,歌登,歌登,歌登,歌登,歌登,歌登
4,年月,平均気温(℃),平均気温(℃),平均気温(℃),平均気温(℃),平均気温(℃),降水量の合計(mm),降水量の合計(mm),降水量の合計(mm),降水量の合計(mm),...,平均気温(℃),平均気温(℃),平均気温(℃),平均気温(℃),平均気温(℃),降水量の合計(mm),降水量の合計(mm),降水量の合計(mm),降水量の合計(mm),降水量の合計(mm)
5,NaN,NaN,NaN,NaN,平年値(℃),平年値(℃),NaN,NaN,NaN,平年値(mm),...,NaN,NaN,NaN,平年値(℃),平年値(℃),NaN,NaN,NaN,平年値(mm),平年値(mm)
6,NaN,NaN,品質情報,均質番号,NaN,品質情報,NaN,品質情報,均質番号,NaN,...,NaN,品質情報,均質番号,NaN,品質情報,NaN,品質情報,均質番号,NaN,品質情報
7,2023/1,-6.1,8,1,-4.5,8,28.5,5,1,23.5,...,-9.9,8,1,-8.2,8,38.5,8,1,98.3,8
8,2023/2,-5.4,8,1,-4.6,8,20.5,8,1,18.4,...,-9.8,8,1,-8.2,8,51.0,8,1,67.3,8
9,2023/3,2.3,8,1,-1.1,8,38.5,8,1,21.5,...,1.4,8,1,-2.9,8,32.5,8,1,71.0,8
10,2023/4,5.0,8,1,3.9,8,75.0,8,1,31.0,...,5.3,8,1,3.6,8,121.0,8,1,55.5,8
11,2023/5,9.6,8,1,8.2,8,17.5,8,1,58.0,...,11.0,8,1,9.5,8,33.0,8,1,69.9,8
12,2023/6,14.2,8,1,11.9,8,101.0,8,1,58.8,...,15.8,8,1,13.4,8,87.5,8,1,82.9,8
13,2023/7,18.6,8,1,16.1,8,191.0,8,1,106.3,...,19.8,8,1,17.4,8,160.5,8,1,119.4,8
14,2023/8,20.3,8,1,18.7,8,303.5,8,1,126.5,...,21.5,8,1,18.9,8,313.0,8,1,149.4,8
15,2023/9,18.7,8,1,16.4,8,55.0,8,1,123.8,...,17.5,8,1,15.1,8,135.5,8,1,157.2,8
16,2023/10,12.1,8,1,10.8,8,96.5,8,1,114.6,...,9.5,8,1,8.5,8,167.5,8,1,145.2,8
17,2023/11,4.5,8,1,3.6,8,295.0,8,1,94.4,...,3.1,8,1,1.7,8,219.5,8,1,157.1,8
18,2023/12,-2.5,8,1,-2.1,8,54.0,8,1,54.0,...,-5.6,8,1,-5.0,8,110.0,8,1,136.4,8

In [3]:
#6行目（ヘッダーなし）に「平年値」の文字列が含まれている行を抽出 （columns_with_heinenchiに条件式の結果がTとなるindexの配列が返る）
columns_with_heinenchi = df.columns[df.iloc[5].str.contains('平年値', na=False)]

df_heinenchi = df[columns_with_heinenchi]

display(df_heinenchi.head(20))
# df_heinenchi.to_csv(os.path.join(output_dir, 'test_filterd.csv'), index=False)

,4,5,9,10,14,15,20,21,22,26,...,112,116,117,122,123,124,128,129,133,134
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,...,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷
3,宗谷岬,宗谷岬,宗谷岬,宗谷岬,稚内,稚内,稚内,稚内,稚内,礼文,...,中頓別,北見枝幸,北見枝幸,北見枝幸,北見枝幸,北見枝幸,歌登,歌登,歌登,歌登
4,平均気温(℃),平均気温(℃),降水量の合計(mm),降水量の合計(mm),平均気温(℃),平均気温(℃),降水量の合計(mm),降水量の合計(mm),降水量の合計(mm),平均気温(℃),...,降水量の合計(mm),平均気温(℃),平均気温(℃),降水量の合計(mm),降水量の合計(mm),降水量の合計(mm),平均気温(℃),平均気温(℃),降水量の合計(mm),降水量の合計(mm)
5,平年値(℃),平年値(℃),平年値(mm),平年値(mm),平年値(℃),平年値(℃),平年値(mm),平年値(mm),平年値(mm),平年値(℃),...,平年値(mm),平年値(℃),平年値(℃),平年値(mm),平年値(mm),平年値(mm),平年値(℃),平年値(℃),平年値(mm),平年値(mm)
6,NaN,品質情報,NaN,品質情報,NaN,品質情報,NaN,現象なし情報,品質情報,NaN,...,品質情報,NaN,品質情報,NaN,現象なし情報,品質情報,NaN,品質情報,NaN,品質情報
7,-4.5,8,23.5,8,-4.3,8,84.6,0,8,-4.6,...,8,-5.5,8,75.6,0,8,-8.2,8,98.3,8
8,-4.6,8,18.4,8,-4.3,8,60.6,0,8,-4.3,...,8,-5.4,8,56.5,0,8,-8.2,8,67.3,8
9,-1.1,8,21.5,8,-0.6,8,55.1,0,8,-0.4,...,8,-1.5,8,64.8,0,8,-2.9,8,71.0,8
10,3.9,8,31.0,8,4.5,8,50.3,0,8,4.1,...,8,4.3,8,56.4,0,8,3.6,8,55.5,8
11,8.2,8,58.0,8,9.1,8,68.1,0,8,8.5,...,8,9.1,8,69.1,0,8,9.5,8,69.9,8
12,11.9,8,58.8,8,13.0,8,65.8,0,8,12.8,...,8,12.4,8,82.4,0,8,13.4,8,82.9,8
13,16.1,8,106.3,8,17.2,8,100.9,0,8,17.3,...,8,16.6,8,125.0,0,8,17.4,8,119.4,8
14,18.7,8,126.5,8,19.5,8,123.1,0,8,19.7,...,8,19.1,8,141.4,0,8,18.9,8,149.4,8
15,16.4,8,123.8,8,17.2,8,136.7,0,8,17.4,...,8,16.5,8,134.9,0,8,15.1,8,157.2,8
16,10.8,8,114.6,8,11.3,8,129.7,0,8,11.2,...,8,10.3,8,127.7,0,8,8.5,8,145.2,8
17,3.6,8,94.4,8,3.8,8,121.4,0,8,3.6,...,8,3.0,8,124.1,0,8,1.7,8,157.1,8
18,-2.1,8,54.0,8,-2.1,8,112.9,0,8,-2.4,...,8,-3.1,8,101.8,0,8,-5.0,8,136.4,8

In [4]:
# 7行目（ヘッダーなし）がNaNのカラム（=データが入っているカラム）について，8〜19行目に1つでも空欄が含まれていれば，4行目の観測地点名を配列にpushする

# 7行目がNaNのカラム（=実際のデータが入っているカラム）を抽出
columns_onlydata = df_heinenchi.columns[df_heinenchi.iloc[6].isna()]
df_onlydata = df[columns_onlydata]

display(df_onlydata)

# # 実データ部分のみをsubset化
data_subset = df_onlydata.iloc[7:18]
# 実データ部分のいずれか1つでもNaNのあるカラムのindexを特定
columns_with_nan = data_subset.columns[data_subset.isna().any()]

display(columns_with_nan)


# # 平年値データに戻り,実データにNaNを含むカラムの都市名を配列にpush
exclude_cities = []

for col in columns_with_nan:
    exclude_cities.append(df_onlydata.loc[3, col])

print(exclude_cities)

,4,9,14,20,26,31,36,41,46,51,...,86,91,96,101,106,111,116,122,128,133
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,...,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷
3,宗谷岬,宗谷岬,稚内,稚内,礼文,礼文,声問,声問,浜鬼志別,浜鬼志別,...,豊富,豊富,浜頓別,浜頓別,中頓別,中頓別,北見枝幸,北見枝幸,歌登,歌登
4,平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),...,平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm)
5,平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),...,平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm)
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,-4.5,23.5,-4.3,84.6,-4.6,73.4,-5.6,NaN,-5.9,61.1,...,-6.1,65.2,-6.3,62.1,-8.4,92.4,-5.5,75.6,-8.2,98.3
8,-4.6,18.4,-4.3,60.6,-4.3,51.6,-5.6,NaN,-6.0,42.7,...,-6.1,48.0,-6.3,46.7,-8.5,66.3,-5.4,56.5,-8.2,67.3
9,-1.1,21.5,-0.6,55.1,-0.4,44.1,-1.5,NaN,-2.1,45.1,...,-1.9,46.5,-2.0,50.2,-3.2,72.2,-1.5,64.8,-2.9,71.0
10,3.9,31.0,4.5,50.3,4.1,49.2,3.7,NaN,3.5,42.7,...,4.1,46.6,4.0,47.6,3.5,56.7,4.3,56.4,3.6,55.5
11,8.2,58.0,9.1,68.1,8.5,79.7,8.9,NaN,8.2,62.5,...,9.6,61.8,9.2,61.0,9.7,68.4,9.1,69.1,9.5,69.9
12,11.9,58.8,13.0,65.8,12.8,84.6,13.1,65.4,11.8,63.0,...,13.7,59.8,12.8,65.0,13.8,66.6,12.4,82.4,13.4,82.9
13,16.1,106.3,17.2,100.9,17.3,101.0,17.2,87.4,15.9,109.2,...,17.9,111.2,16.9,116.9,17.9,120.2,16.6,125.0,17.4,119.4
14,18.7,126.5,19.5,123.1,19.7,138.6,19.2,113.4,18.4,125.7,...,19.4,120.9,19.0,118.9,19.1,145.5,19.1,141.4,18.9,149.4
15,16.4,123.8,17.2,136.7,17.4,131.1,16.0,127.8,15.5,119.6,...,16.0,130.8,15.8,121.4,15.0,141.8,16.5,134.9,15.1,157.2
16,10.8,114.6,11.3,129.7,11.2,100.4,9.8,NaN,9.4,118.0,...,9.7,137.8,9.6,106.4,8.4,155.8,10.3,127.7,8.5,145.2
17,3.6,94.4,3.8,121.4,3.6,98.4,2.9,NaN,2.2,110.6,...,2.7,116.6,2.4,101.9,1.5,152.8,3.0,124.1,1.7,157.1
18,-2.1,54.0,-2.1,112.9,-2.4,91.5,-2.8,NaN,-3.5,91.2,...,-3.4,85.9,-3.8,83.3,-5.3,126.1,-3.1,101.8,-5.0,136.4

Index([41, 61], dtype='int64')

['声問', '本泊']

In [42]:
# exclude_citiesに含まれている都市のデータを,気温降水量共に除外する

# 都市名をデータフレームのインデックスと共に抽出
city_name = df_onlydata.loc[3]

# exclude_citiesに名前が登録されている都市の,データフレームのカラムindexを配列で取得
exclude_indexes = city_name[city_name.isin(exclude_cities)].index

# 除外するカラムindexでフィルタリング
filtered_df = df_onlydata.drop(columns=exclude_indexes)
display(filtered_df)


# 仕上げ
# 1,2,7行目を削除
final_df = filtered_df.drop([0,1,6])

display(final_df)

# 行と列の見出しを除いて出力
# final_df.to_csv(os.path.join(output_dir, 'final_df.csv'), index=False, header=False)

,4,9,14,20,26,31,46,51,66,71,...,86,91,96,101,106,111,116,122,128,133
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,...,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷
3,宗谷岬,宗谷岬,稚内,稚内,礼文,礼文,浜鬼志別,浜鬼志別,沼川,沼川,...,豊富,豊富,浜頓別,浜頓別,中頓別,中頓別,北見枝幸,北見枝幸,歌登,歌登
4,平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),...,平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm)
5,平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),...,平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm)
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,-4.5,23.5,-4.3,84.6,-4.6,73.4,-5.9,61.1,-6.9,89.2,...,-6.1,65.2,-6.3,62.1,-8.4,92.4,-5.5,75.6,-8.2,98.3
8,-4.6,18.4,-4.3,60.6,-4.3,51.6,-6.0,42.7,-6.9,66.5,...,-6.1,48.0,-6.3,46.7,-8.5,66.3,-5.4,56.5,-8.2,67.3
9,-1.1,21.5,-0.6,55.1,-0.4,44.1,-2.1,45.1,-2.5,59.0,...,-1.9,46.5,-2.0,50.2,-3.2,72.2,-1.5,64.8,-2.9,71.0
10,3.9,31.0,4.5,50.3,4.1,49.2,3.5,42.7,3.5,52.5,...,4.1,46.6,4.0,47.6,3.5,56.7,4.3,56.4,3.6,55.5
11,8.2,58.0,9.1,68.1,8.5,79.7,8.2,62.5,8.9,66.1,...,9.6,61.8,9.2,61.0,9.7,68.4,9.1,69.1,9.5,69.9
12,11.9,58.8,13.0,65.8,12.8,84.6,11.8,63.0,12.9,60.5,...,13.7,59.8,12.8,65.0,13.8,66.6,12.4,82.4,13.4,82.9
13,16.1,106.3,17.2,100.9,17.3,101.0,15.9,109.2,17.1,109.1,...,17.9,111.2,16.9,116.9,17.9,120.2,16.6,125.0,17.4,119.4
14,18.7,126.5,19.5,123.1,19.7,138.6,18.4,125.7,18.7,125.5,...,19.4,120.9,19.0,118.9,19.1,145.5,19.1,141.4,18.9,149.4
15,16.4,123.8,17.2,136.7,17.4,131.1,15.5,119.6,15.0,128.6,...,16.0,130.8,15.8,121.4,15.0,141.8,16.5,134.9,15.1,157.2
16,10.8,114.6,11.3,129.7,11.2,100.4,9.4,118.0,8.8,142.0,...,9.7,137.8,9.6,106.4,8.4,155.8,10.3,127.7,8.5,145.2
17,3.6,94.4,3.8,121.4,3.6,98.4,2.2,110.6,1.9,130.6,...,2.7,116.6,2.4,101.9,1.5,152.8,3.0,124.1,1.7,157.1
18,-2.1,54.0,-2.1,112.9,-2.4,91.5,-3.5,91.2,-4.1,117.9,...,-3.4,85.9,-3.8,83.3,-5.3,126.1,-3.1,101.8,-5.0,136.4

,4,9,14,20,26,31,46,51,66,71,...,86,91,96,101,106,111,116,122,128,133
2,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,...,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷
3,宗谷岬,宗谷岬,稚内,稚内,礼文,礼文,浜鬼志別,浜鬼志別,沼川,沼川,...,豊富,豊富,浜頓別,浜頓別,中頓別,中頓別,北見枝幸,北見枝幸,歌登,歌登
4,平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),...,平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm)
5,平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),...,平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm)
7,-4.5,23.5,-4.3,84.6,-4.6,73.4,-5.9,61.1,-6.9,89.2,...,-6.1,65.2,-6.3,62.1,-8.4,92.4,-5.5,75.6,-8.2,98.3
8,-4.6,18.4,-4.3,60.6,-4.3,51.6,-6.0,42.7,-6.9,66.5,...,-6.1,48.0,-6.3,46.7,-8.5,66.3,-5.4,56.5,-8.2,67.3
9,-1.1,21.5,-0.6,55.1,-0.4,44.1,-2.1,45.1,-2.5,59.0,...,-1.9,46.5,-2.0,50.2,-3.2,72.2,-1.5,64.8,-2.9,71.0
10,3.9,31.0,4.5,50.3,4.1,49.2,3.5,42.7,3.5,52.5,...,4.1,46.6,4.0,47.6,3.5,56.7,4.3,56.4,3.6,55.5
11,8.2,58.0,9.1,68.1,8.5,79.7,8.2,62.5,8.9,66.1,...,9.6,61.8,9.2,61.0,9.7,68.4,9.1,69.1,9.5,69.9
12,11.9,58.8,13.0,65.8,12.8,84.6,11.8,63.0,12.9,60.5,...,13.7,59.8,12.8,65.0,13.8,66.6,12.4,82.4,13.4,82.9
13,16.1,106.3,17.2,100.9,17.3,101.0,15.9,109.2,17.1,109.1,...,17.9,111.2,16.9,116.9,17.9,120.2,16.6,125.0,17.4,119.4
14,18.7,126.5,19.5,123.1,19.7,138.6,18.4,125.7,18.7,125.5,...,19.4,120.9,19.0,118.9,19.1,145.5,19.1,141.4,18.9,149.4
15,16.4,123.8,17.2,136.7,17.4,131.1,15.5,119.6,15.0,128.6,...,16.0,130.8,15.8,121.4,15.0,141.8,16.5,134.9,15.1,157.2
16,10.8,114.6,11.3,129.7,11.2,100.4,9.4,118.0,8.8,142.0,...,9.7,137.8,9.6,106.4,8.4,155.8,10.3,127.7,8.5,145.2
17,3.6,94.4,3.8,121.4,3.6,98.4,2.2,110.6,1.9,130.6,...,2.7,116.6,2.4,101.9,1.5,152.8,3.0,124.1,1.7,157.1
18,-2.1,54.0,-2.1,112.9,-2.4,91.5,-3.5,91.2,-4.1,117.9,...,-3.4,85.9,-3.8,83.3,-5.3,126.1,-3.1,101.8,-5.0,136.4

In [58]:
# 2列にわたるデータから,都府県名,観測所名,temp,rainデータを抜き出して1つの配列にまとめる
area_and_name = final_df.iloc[0:2, 0]
temp = final_df.iloc[4:16, 0]
rain = final_df.iloc[4:16, 1]

new_row = pd.concat([area_and_name, temp, rain])
display(new_row)

# 新しいデータフレームを作成
new_df = pd.DataFrame(columns=range(0,26))
# ヘッダーを追加
header = ['都府県・振興局', '観測所名', 
          'temp_jan', 'temp_feb', 'temp_mar', 'temp_apr', 'temp_may', 'temp_jun',
          'temp_jul', 'temp_aug', 'temp_sep', 'temp_oct', 'temp_nov', 'temp_dec',
          'rain_jan', 'rain_feb', 'rain_mar', 'rain_apr', 'rain_may', 'rain_jun',
          'rain_jul', 'rain_aug', 'rain_sep', 'rain_oct', 'rain_nov', 'rain_dec']
new_df.loc[0] = header
display(new_df)

# 作成したデータ配列を,データフレームの最後尾に格納（len(new_df)で既存配列の「長さ」を返すので,index指定で最後尾となる)
new_df.loc[len(new_df)] = new_row.T.values   # Tで縦横変換
display(new_df)

# new_df.to_csv(os.path.join(output_dir, 'new_df.csv'), index=False, header=False)

2        宗谷
3       宗谷岬
7      -4.5
8      -4.6
9      -1.1
10      3.9
11      8.2
12     11.9
13     16.1
14     18.7
15     16.4
16     10.8
17      3.6
18     -2.1
7      23.5
8      18.4
9      21.5
10     31.0
11     58.0
12     58.8
13    106.3
14    126.5
15    123.8
16    114.6
17     94.4
18     54.0
dtype: object

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,都府県・振興局,観測所名,temp_jan,temp_feb,temp_mar,temp_apr,temp_may,temp_jun,temp_jul,temp_aug,...,rain_mar,rain_apr,rain_may,rain_jun,rain_jul,rain_aug,rain_sep,rain_oct,rain_nov,rain_dec

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,都府県・振興局,観測所名,temp_jan,temp_feb,temp_mar,temp_apr,temp_may,temp_jun,temp_jul,temp_aug,...,rain_mar,rain_apr,rain_may,rain_jun,rain_jul,rain_aug,rain_sep,rain_oct,rain_nov,rain_dec
1,宗谷,宗谷岬,-4.5,-4.6,-1.1,3.9,8.2,11.9,16.1,18.7,...,21.5,31.0,58.0,58.8,106.3,126.5,123.8,114.6,94.4,54.0

In [52]:
new_df = pd.DataFrame(columns=range(0,26))
display(new_df)

len(new_df)

new_df.loc[0] = new_row.T.values
display(new_df)

len(new_df)

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
Index: []

[0 rows x 26 columns]

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,宗谷,宗谷岬,-4.5,-4.6,-1.1,3.9,8.2,11.9,16.1,18.7,...,21.5,31.0,58.0,58.8,106.3,126.5,123.8,114.6,94.4,54.0

1