In [1]:
#現在のディレクトリを確認
import os
current_directory = os.getcwd()
print("Current working directory:", current_directory)

Current working directory: /Users/sawad/dev/myapps/u-on-zu_data-processing

In [2]:
#出力先ディレクトリの設定
output_dir = './processed'

In [7]:
import pandas as pd

df=pd.read_csv('./raw/utf-8/18_根室_utf-8.csv', encoding='utf-8', header=None)

display(df.head(30))

,0,1,2,3,4,5,6,7,8,9,...,83,84,85,86,87,88,89,90,91,92
0,ダウンロードした時刻：2024/06/06 20:29:22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,根室,根室,根室,根室,根室,根室,根室,根室,根室,...,根室,根室,根室,根室,根室,根室,根室,根室,根室,根室
3,NaN,羅臼,羅臼,羅臼,羅臼,羅臼,羅臼,羅臼,羅臼,羅臼,...,厚床,厚床,厚床,厚床,厚床,厚床,厚床,厚床,厚床,厚床
4,年月,降水量の合計(mm),降水量の合計(mm),降水量の合計(mm),降水量の合計(mm),降水量の合計(mm),平均気温(℃),平均気温(℃),平均気温(℃),平均気温(℃),...,降水量の合計(mm),降水量の合計(mm),降水量の合計(mm),降水量の合計(mm),降水量の合計(mm),平均気温(℃),平均気温(℃),平均気温(℃),平均気温(℃),平均気温(℃)
5,NaN,NaN,NaN,NaN,平年値(mm),平年値(mm),NaN,NaN,NaN,平年値(℃),...,NaN,NaN,NaN,平年値(mm),平年値(mm),NaN,NaN,NaN,平年値(℃),平年値(℃)
6,NaN,NaN,品質情報,均質番号,NaN,品質情報,NaN,品質情報,均質番号,NaN,...,NaN,品質情報,均質番号,NaN,品質情報,NaN,品質情報,均質番号,NaN,品質情報
7,2023/1,75.0,8,1,89.7,8,-5.6,8,1,-4.5,...,12.0,8,1,37.2,8,-7.6,8,1,-6.0,8
8,2023/2,56.0,8,1,66.6,8,-5.5,8,1,-4.8,...,18.5,8,1,27.7,8,-6.7,8,1,-5.8,8
9,2023/3,102.0,8,1,93.9,8,1.4,8,1,-1.1,...,90.5,8,1,57.8,8,1.4,8,1,-1.7,8
10,2023/4,178.0,8,1,111.7,8,5.4,8,1,2.9,...,147.5,8,1,78.8,8,5.7,8,1,3.3,8
11,2023/5,30.5,8,1,144.0,8,9.5,8,1,7.8,...,50.0,8,1,110.2,8,9.5,8,1,7.9,8
12,2023/6,91.0,8,1,119.4,8,14.1,8,1,11.5,...,44.5,8,1,117.1,8,14.4,8,1,11.5,8
13,2023/7,105.0,8,1,125.4,8,18.9,8,1,15.4,...,117.5,8,1,124.7,8,19.1,5,1,15.4,8
14,2023/8,141.5,8,1,200.5,8,21.2,8,1,17.8,...,59.5,8,1,142.6,8,21.5,8,1,17.5,8
15,2023/9,200.5,8,1,204.7,8,18.8,8,1,15.7,...,140.0,8,1,172.9,8,18.9,8,1,15.4,8
16,2023/10,160.0,8,1,214.1,8,11.6,8,1,10.1,...,66.0,5,1,137.0,8,11.0,5,1,9.9,8
17,2023/11,115.5,8,1,150.7,8,6.0,8,1,4.1,...,51.0,8,1,85.3,8,5.7,8,1,3.6,8
18,2023/12,91.5,8,1,133.8,8,-1.7,8,1,-1.4,...,42.5,8,1,67.5,8,-3.0,8,1,-3.1,8

In [8]:
#6行目（ヘッダーなし）に「平年値」の文字列が含まれている行を抽出 （columns_with_heinenchiに条件式の結果がTとなるindexの配列が返る）
columns_with_heinenchi = df.columns[df.iloc[5].str.contains('平年値', na=False)]

df_heinenchi = df[columns_with_heinenchi]

display(df_heinenchi.head(20))
# df_heinenchi.to_csv(os.path.join(output_dir, 'test_filterd.csv'), index=False)

,4,5,9,10,14,15,19,20,24,25,...,71,72,76,77,81,82,86,87,91,92
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,根室,根室,根室,根室,根室,根室,根室,根室,根室,根室,...,根室,根室,根室,根室,根室,根室,根室,根室,根室,根室
3,羅臼,羅臼,羅臼,羅臼,標津,標津,標津,標津,上標津,上標津,...,根室,根室,納沙布,納沙布,納沙布,納沙布,厚床,厚床,厚床,厚床
4,降水量の合計(mm),降水量の合計(mm),平均気温(℃),平均気温(℃),降水量の合計(mm),降水量の合計(mm),平均気温(℃),平均気温(℃),降水量の合計(mm),降水量の合計(mm),...,平均気温(℃),平均気温(℃),降水量の合計(mm),降水量の合計(mm),平均気温(℃),平均気温(℃),降水量の合計(mm),降水量の合計(mm),平均気温(℃),平均気温(℃)
5,平年値(mm),平年値(mm),平年値(℃),平年値(℃),平年値(mm),平年値(mm),平年値(℃),平年値(℃),平年値(mm),平年値(mm),...,平年値(℃),平年値(℃),平年値(mm),平年値(mm),平年値(℃),平年値(℃),平年値(mm),平年値(mm),平年値(℃),平年値(℃)
6,NaN,品質情報,NaN,品質情報,NaN,品質情報,NaN,品質情報,NaN,品質情報,...,NaN,品質情報,NaN,品質情報,NaN,品質情報,NaN,品質情報,NaN,品質情報
7,89.7,8,-4.5,8,38.0,8,-5.4,8,45.1,8,...,-3.4,8,18.9,8,-3.0,8,37.2,8,-6.0,8
8,66.6,8,-4.8,8,28.0,8,-5.5,8,37.9,8,...,-3.8,8,14.6,8,-3.7,8,27.7,8,-5.8,8
9,93.9,8,-1.1,8,54.3,8,-1.6,8,57.8,8,...,-0.8,8,37.4,8,-1.0,8,57.8,8,-1.7,8
10,111.7,8,2.9,8,82.8,8,3.4,8,85.4,8,...,3.5,8,53.9,8,3.0,8,78.8,8,3.3,8
11,144.0,8,7.8,8,109.8,8,8.1,8,108.6,8,...,7.7,8,82.9,8,6.8,8,110.2,8,7.9,8
12,119.4,8,11.5,8,111.9,8,11.5,8,107.6,8,...,10.9,8,93.6,8,10.1,8,117.1,8,11.5,8
13,125.4,8,15.4,8,123.1,8,15.4,8,124.5,8,...,14.9,8,107.7,8,14.0,8,124.7,8,15.4,8
14,200.5,8,17.8,8,161.2,8,18.0,8,192.5,8,...,17.4,8,116.3,8,16.8,8,142.6,8,17.5,8
15,204.7,8,15.7,8,174.5,8,16.1,8,152.9,8,...,16.2,8,130.6,8,16.0,8,172.9,8,15.4,8
16,214.1,8,10.1,8,125.2,8,10.4,8,124.1,8,...,11.6,8,103.3,8,11.7,8,137.0,8,9.9,8
17,150.7,8,4.1,8,78.5,8,3.8,8,80.9,8,...,5.6,8,75.2,8,5.8,8,85.3,8,3.6,8
18,133.8,8,-1.4,8,62.4,8,-2.6,8,73.4,8,...,-0.5,8,49.2,8,-0.2,8,67.5,8,-3.1,8

In [35]:
# 7行目（ヘッダーなし）がNaNのカラム（=データが入っているカラム）について，8〜19行目に1つでも空欄が含まれていれば，4行目の観測地点名を配列にpushする

# 除外都市リストを宣言
exclude_cities = []

# 7行目がNaNのカラム（=実際のデータが入っているカラム）を抽出
columns_onlydata = df_heinenchi.columns[df_heinenchi.iloc[6].isna()]
df_onlydata = df[columns_onlydata]
# display(df_onlydata)

# 実データ部分のみをsubset化
data_subset = df_onlydata.iloc[7:18]
# 実データ部分のいずれか1つでもNaNのあるカラムのindexを特定
columns_with_nan = data_subset.columns[data_subset.isna().any()]
display(columns_with_nan)


# 平年値データに戻り,実データにNaNを含むカラムの都市名を配列にpush
for col in columns_with_nan:
    exclude_cities.append(df_onlydata.loc[3, col])

print(exclude_cities)


# 「品質情報」のカラムを抜き出し,8〜19行目に1つでも「8」以外の数値が含まれていれば，4行目の観測地点名を配列にpushする
columns_onlyquality = df_heinenchi.columns[df_heinenchi.iloc[6].str.contains('品質情報', na=False)]
df_onlyquality = df[columns_onlyquality]
# display(df_onlyquality)

# 品質情報の実データ部分のみを抽出
data_quality_subset = df_onlyquality.iloc[7:18]
# display(data_quality_subset)

# 実データ部分のいずれか1つでも8以外のあるカラムのindexを特定
data_quality_subset = data_quality_subset.astype(int)  # int型に変換
columns_with_notok = data_quality_subset.columns[(data_quality_subset != 8).any()]
# display(columns_with_notok)

# 平年値データに戻り,8以外のあるカラムの都市名を配列にpush
for col in columns_with_notok:
    exclude_cities.append(df_onlyquality.loc[3, col])

print(exclude_cities)

# 重複を除外しておく
exclude_cities = list(set(exclude_cities))
print(exclude_cities)

Index([41, 61], dtype='int64')

['声問', '本泊']
['声問', '本泊', '声問', '本泊']
['声問', '本泊']

In [36]:
# exclude_citiesに含まれている都市のデータを,気温・降水量共に除外する

# データフレームから都市名の行をインデックスと共に抽出
city_name = df_onlydata.loc[3]

# exclude_citiesに名前が登録されている都市の,データフレームのカラムindexを配列で取得
exclude_indexes = city_name[city_name.isin(exclude_cities)].index

# 除外するカラムindexでフィルタリング
filtered_df = df_onlydata.drop(columns=exclude_indexes)

# 仕上げ
# 1,2,7行目を削除
final_df = filtered_df.drop([0,1,6])
display(final_df)

# 行と列の見出しを除いて出力
# final_df.to_csv(os.path.join(output_dir, 'final_df.csv'), index=False, header=False)

,4,9,14,20,26,31,46,51,66,71,...,86,91,96,101,106,111,116,122,128,133
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,...,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷
3,宗谷岬,宗谷岬,稚内,稚内,礼文,礼文,浜鬼志別,浜鬼志別,沼川,沼川,...,豊富,豊富,浜頓別,浜頓別,中頓別,中頓別,北見枝幸,北見枝幸,歌登,歌登
4,平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),...,平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm)
5,平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),...,平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm)
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,-4.5,23.5,-4.3,84.6,-4.6,73.4,-5.9,61.1,-6.9,89.2,...,-6.1,65.2,-6.3,62.1,-8.4,92.4,-5.5,75.6,-8.2,98.3
8,-4.6,18.4,-4.3,60.6,-4.3,51.6,-6.0,42.7,-6.9,66.5,...,-6.1,48.0,-6.3,46.7,-8.5,66.3,-5.4,56.5,-8.2,67.3
9,-1.1,21.5,-0.6,55.1,-0.4,44.1,-2.1,45.1,-2.5,59.0,...,-1.9,46.5,-2.0,50.2,-3.2,72.2,-1.5,64.8,-2.9,71.0
10,3.9,31.0,4.5,50.3,4.1,49.2,3.5,42.7,3.5,52.5,...,4.1,46.6,4.0,47.6,3.5,56.7,4.3,56.4,3.6,55.5
11,8.2,58.0,9.1,68.1,8.5,79.7,8.2,62.5,8.9,66.1,...,9.6,61.8,9.2,61.0,9.7,68.4,9.1,69.1,9.5,69.9
12,11.9,58.8,13.0,65.8,12.8,84.6,11.8,63.0,12.9,60.5,...,13.7,59.8,12.8,65.0,13.8,66.6,12.4,82.4,13.4,82.9
13,16.1,106.3,17.2,100.9,17.3,101.0,15.9,109.2,17.1,109.1,...,17.9,111.2,16.9,116.9,17.9,120.2,16.6,125.0,17.4,119.4
14,18.7,126.5,19.5,123.1,19.7,138.6,18.4,125.7,18.7,125.5,...,19.4,120.9,19.0,118.9,19.1,145.5,19.1,141.4,18.9,149.4
15,16.4,123.8,17.2,136.7,17.4,131.1,15.5,119.6,15.0,128.6,...,16.0,130.8,15.8,121.4,15.0,141.8,16.5,134.9,15.1,157.2
16,10.8,114.6,11.3,129.7,11.2,100.4,9.4,118.0,8.8,142.0,...,9.7,137.8,9.6,106.4,8.4,155.8,10.3,127.7,8.5,145.2
17,3.6,94.4,3.8,121.4,3.6,98.4,2.2,110.6,1.9,130.6,...,2.7,116.6,2.4,101.9,1.5,152.8,3.0,124.1,1.7,157.1
18,-2.1,54.0,-2.1,112.9,-2.4,91.5,-3.5,91.2,-4.1,117.9,...,-3.4,85.9,-3.8,83.3,-5.3,126.1,-3.1,101.8,-5.0,136.4

,4,9,14,20,26,31,46,51,66,71,...,86,91,96,101,106,111,116,122,128,133
2,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,...,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷,宗谷
3,宗谷岬,宗谷岬,稚内,稚内,礼文,礼文,浜鬼志別,浜鬼志別,沼川,沼川,...,豊富,豊富,浜頓別,浜頓別,中頓別,中頓別,北見枝幸,北見枝幸,歌登,歌登
4,平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),...,平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm),平均気温(℃),降水量の合計(mm)
5,平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),...,平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm),平年値(℃),平年値(mm)
7,-4.5,23.5,-4.3,84.6,-4.6,73.4,-5.9,61.1,-6.9,89.2,...,-6.1,65.2,-6.3,62.1,-8.4,92.4,-5.5,75.6,-8.2,98.3
8,-4.6,18.4,-4.3,60.6,-4.3,51.6,-6.0,42.7,-6.9,66.5,...,-6.1,48.0,-6.3,46.7,-8.5,66.3,-5.4,56.5,-8.2,67.3
9,-1.1,21.5,-0.6,55.1,-0.4,44.1,-2.1,45.1,-2.5,59.0,...,-1.9,46.5,-2.0,50.2,-3.2,72.2,-1.5,64.8,-2.9,71.0
10,3.9,31.0,4.5,50.3,4.1,49.2,3.5,42.7,3.5,52.5,...,4.1,46.6,4.0,47.6,3.5,56.7,4.3,56.4,3.6,55.5
11,8.2,58.0,9.1,68.1,8.5,79.7,8.2,62.5,8.9,66.1,...,9.6,61.8,9.2,61.0,9.7,68.4,9.1,69.1,9.5,69.9
12,11.9,58.8,13.0,65.8,12.8,84.6,11.8,63.0,12.9,60.5,...,13.7,59.8,12.8,65.0,13.8,66.6,12.4,82.4,13.4,82.9
13,16.1,106.3,17.2,100.9,17.3,101.0,15.9,109.2,17.1,109.1,...,17.9,111.2,16.9,116.9,17.9,120.2,16.6,125.0,17.4,119.4
14,18.7,126.5,19.5,123.1,19.7,138.6,18.4,125.7,18.7,125.5,...,19.4,120.9,19.0,118.9,19.1,145.5,19.1,141.4,18.9,149.4
15,16.4,123.8,17.2,136.7,17.4,131.1,15.5,119.6,15.0,128.6,...,16.0,130.8,15.8,121.4,15.0,141.8,16.5,134.9,15.1,157.2
16,10.8,114.6,11.3,129.7,11.2,100.4,9.4,118.0,8.8,142.0,...,9.7,137.8,9.6,106.4,8.4,155.8,10.3,127.7,8.5,145.2
17,3.6,94.4,3.8,121.4,3.6,98.4,2.2,110.6,1.9,130.6,...,2.7,116.6,2.4,101.9,1.5,152.8,3.0,124.1,1.7,157.1
18,-2.1,54.0,-2.1,112.9,-2.4,91.5,-3.5,91.2,-4.1,117.9,...,-3.4,85.9,-3.8,83.3,-5.3,126.1,-3.1,101.8,-5.0,136.4

In [9]:

# 新しいデータフレームを作成
new_df = pd.DataFrame(columns=range(0,26))
# ヘッダーを追加
header = ['都府県・振興局', '観測所名', 
          'temp_jan', 'temp_feb', 'temp_mar', 'temp_apr', 'temp_may', 'temp_jun',
          'temp_jul', 'temp_aug', 'temp_sep', 'temp_oct', 'temp_nov', 'temp_dec',
          'rain_jan', 'rain_feb', 'rain_mar', 'rain_apr', 'rain_may', 'rain_jun',
          'rain_jul', 'rain_aug', 'rain_sep', 'rain_oct', 'rain_nov', 'rain_dec']
new_df.loc[0] = header
display(new_df)


#繰り返し処理で,2列のデータをまとめて完成版データフレームにappendする
# 列を2つずつ繰り返し処理
for i in range(0, final_df.shape[1], 2):      #.shape[1]で列数を返す
    
    # 2列にわたるデータから,都府県名,観測所名,temp,rainデータを抜き出して1つの配列にまとめる
    area_and_name = final_df.iloc[0:2, i]
    temp = final_df.iloc[4:16, i]
    rain = final_df.iloc[4:16, i+1]

    new_row = pd.concat([area_and_name, temp, rain])
    display(new_row)
    
    # 作成したデータ配列を,データフレームの最後尾に格納（len(new_df)で既存配列の「長さ」を返すので,index指定で最後尾となる)
    new_df.loc[len(new_df)] = new_row.T.values   # Tで縦横変換


display(new_df)

new_df.to_csv(os.path.join(output_dir, 'new_df.csv'), index=False, header=False)

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,都府県振興局,観測所名,temp_jan,temp_feb,temp_mar,temp_apr,temp_may,temp_jun,temp_jul,temp_aug,...,rain_mar,rain_apr,rain_may,rain_jun,rain_jul,rain_aug,rain_sep,rain_oct,rain_nov,rain_dec

NameError: name 'final_df' is not defined